battlefield:
  length: 10
  width: 10
guns:
  - posX: 2
    posY: 0
    protectionLevel: 20
    quantityBurstingCassette: 2
    capacityBurstingCassette: 5
    quantityArmorPiercingCassette: 20
    capacityArmorPiercingCassette: 10
  - posX: 5
    posY: 0
    protectionLevel: 20
    quantityBurstingCassette: 2
    capacityBurstingCassette: 5
    quantityArmorPiercingCassette: 20
    capacityArmorPiercingCassette: 10
  - posX: 8
    posY: 0
    protectionLevel: 20
    quantityBurstingCassette: 2
    capacityBurstingCassette: 5
    quantityArmorPiercingCassette: 20
    capacityArmorPiercingCassette: 10
enemies:
  - posX: 1
    posY: 2
    protectionLevel: 10
    type: TANK
  - posX: 6
    posY: 3
    protectionLevel: 10
    type: TANK
  - posX: 8
    posY: 7
    protectionLevel: 10
    type: TANK
  - posX: 4
    posY: 8
    protectionLevel: 10
    type: TANK
  - posX: 5
    posY: 5
    protectionLevel: 20
    type: INFANTRY
  - posX: 1
    posY: 4
    protectionLevel: 20
    type: INFANTRY
  - posX: 8
    posY: 2
    protectionLevel: 20
    type: INFANTRY
  - posX: 2
    posY: 7
    protectionLevel: 20
    type: INFANTRY