battlefield:
  length: 50
  width: 10
guns:
  - posX: 2
    posY: 0
    protectionLevel: 20
    quantityBurstingCassette: 40
    capacityBurstingCassette: 15
    quantityArmorPiercingCassette: 40
    capacityArmorPiercingCassette: 10
#  - posX: 5
#    posY: 0
#    protectionLevel: 20
#    quantityBurstingCassette: 5
#    capacityBurstingCassette: 5
#    quantityArmorPiercingCassette: 10
#    capacityArmorPiercingCassette: 10
#  - posX: 8
#    posY: 0
#    protectionLevel: 20
#    quantityBurstingCassette: 5
#    capacityBurstingCassette: 5
#    quantityArmorPiercingCassette: 10
#    capacityArmorPiercingCassette: 10
enemies:
  - type: TANK
    posX: 1
    posY: 48
    protectionLevel: 10
    speed: 4
  - type: TANK
    posX: 3
    posY: 48
    protectionLevel: 10
    speed: 5
  - type: TANK
    posX: 5
    posY: 48
    protectionLevel: 10
    speed: 3
  - type: TANK
    posX: 7
    posY: 48
    protectionLevel: 10
    speed: 4
  - type: INFANTRY
    posX: 2
    posY: 49
    protectionLevel: 5
    speed: 3
  - type: INFANTRY
    posX: 4
    posY: 49
    protectionLevel: 5
    speed: 3
  - type: INFANTRY
    posX: 6
    posY: 49
    protectionLevel: 5
    speed: 3
  - type: INFANTRY
    posX: 8
    posY: 49
    protectionLevel: 5
    speed: 3